notifications:
    commits:      commits@age.apache.org
    pullrequests: commits@age.apache.org

github:
  features:
    wiki: true
    issues: true
    projects: true
    discussions: true

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true
